name: Deploy to Unihost 🚀

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Скачиваем код
    - name: Checkout 🛎️
      uses: actions/checkout@v4

    # 2. Устанавливаем Node.js
    - name: Setup Node.js ⚙️
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 3. Собираем сайт
    - name: Install and Build 🔧
      run: |
        npm install
        npm run build

    # 4. Отправляем на сервер (С отключенной проверкой ключей)
    - name: Deploy via SCP 📦
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "dist/*"
        target: "www/ciacademy.kz"
        strip_components: 1
        debug: true  # Покажет подробности, если что-то не так
        command_timeout: 30m
